# Práctica VI

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/javism/fi2022-2023/blob/main/practica06/practica06.ipynb)

* Vectores y Matrices: almacenan este tipo de datos con contenido numérico (bool, int, float). Habitualmente no añadimos y quitamos elementos salvo con operaciones puntuales de contatenación. 
* Listas: tipo de datos para almacenar otros datos de cualquier tipo. Están diseñados como estructura dinámica en la que añadir y extraer elementos habitualmente. 

Recursos: 
* [Cómo resolver sistemas de ecuaciones lineales con numpy](https://joanby.github.io/bookdown-algebra/ecuaciones-y-sistemas-lineales-con-r-python-y-octave.html#trabajando-con-python)

## Vectores y Matrices

Utilizaremos la biblioteca `numpy` para crear matrices y vector. Por convención siempre se nombra como `np`

Crear una matriz o vector con valores concretos. Observa las diferentes formas (`shape`) que adquieren. 

In [22]:
import numpy as np

# Vector
M = np.array([1,2,3])
print(M)
print(M.shape)

# "Matriz"
M = np.array([[1,2,3]])
print(M)
print(M.shape)

# Matriz
M = np.array([[1,2,3],[4,5,6]])
print(M)
print(M.shape)

# "Matriz"
M = np.array([[1],[2],[3]])
print(M)
print(M.shape)


[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1]
 [2]
 [3]]
(3, 1)


Otra opción para crear matrices es directamente crearlas con ceros, unos o números aleatorios

In [23]:
M = np.zeros(3)
print(M)
M = np.zeros([3,3])
print(M)

# Observa las diferencias
z = np.zeros([3])
z
z = np.zeros([3,1])
z
z = np.ones([3,2])
print(z)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


El módulo `np.random` nos permite generar (o muestrear) números alatorios de distintas distribuciones. Por defecto se usa la distribución uniforme para generar números en 0 y 1, pero también se pueden generar enteros de la uniforme u otros números de la distribución normal, Poison, etc. 

In [24]:
M = np.random.random([1,4])
M

array([[0.59139526, 0.19773657, 0.1629087 , 0.86775647]])

In [25]:
M = np.random.randint(-10,10,(3,4))
M

array([[  6,   3,  -7,   9],
       [ -2,   9,  -1,   2],
       [ -7,   9, -10,  -2]])

In [26]:
# Números aleatorios con la distribución normal con media 3 y varianza 2
Mn = np.random.normal(3, 2, (3,4))
Mn

array([[ 2.07851931,  4.13154333,  0.03125711,  5.13203979],
       [ 3.54035778,  5.59426043,  4.24266025, -0.96119269],
       [ 4.29425355,  5.25114221,  5.8375844 , -0.41234678]])

### Acceso a elementos de la matriz

Ejemplos básicos para acceder a:
* la primera fila de la matriz completa
* el primer elemento de la primera fila de la matriz
* la primera fila de la matriz completa explícitamente con :
* la primera columna de la matriz
* la última columna de la matriz (podríamos poner -2, -3, etc.)

In [27]:
print(M)

[[  6   3  -7   9]
 [ -2   9  -1   2]
 [ -7   9 -10  -2]]


In [28]:
M[0,]

array([ 6,  3, -7,  9])

In [29]:
M[0,0]

6

In [30]:
M[0,:]

array([ 6,  3, -7,  9])

In [31]:
M[:,0]

array([ 6, -2, -7])

In [32]:
M[:,-1]

array([ 9,  2, -2])

In [33]:
vector = M[2,:]
vector

array([ -7,   9, -10,  -2])

### Contatenar matrices

Se pueden concatenar matrices siempre que las dimensiones de las matrices cumplan las condiciones de álgebra lineal

In [34]:
M1 = np.array([1,2,3])
M2 = np.array([3, -4, 5, 6])
M3 = np.concatenate([M1,M2])
print(M3)

# Esto generaría un error
#M1 = np.array([[1,2,3]])
#M2 = np.array([3, -4, 5, 6])
#M3 = np.concatenate([M1,M2])

[ 1  2  3  3 -4  5  6]


## Recorrido de vectores y matrices
* Métodos de crear vectores/matrices: `np.array`, `np.zeros`...
* Forma matrices: `shape` devuelve un vector de dos elementos con el número de filas [0] y columnas [1]

In [35]:
v1 = np.array([5, 1, 3, 15, 4])
v2 = np.array([5, 1, 3, 15, 4, 3, 4, 2])
print(v1)
print(v2)

v3 = np.concatenate((v1,v2))

print(v3)
# Dimensiones vector y su longitud
print(f'Forma: {v3.shape}')
print(f'Longitud vector {v3.shape[0]}')

[ 5  1  3 15  4]
[ 5  1  3 15  4  3  4  2]
[ 5  1  3 15  4  5  1  3 15  4  3  4  2]
Forma: (13,)
Longitud vector 13


Podemos recorrer los vectores/matrices con un iterador que extrae cada elemento o utilizando las coordenadas 

In [36]:

for x in v1: 
    print(x)
    
for i in range(v1.shape[0]):
    print(v1[i])

for i in range(v1.shape[0]):
    print(f'v1[{i}]={v1[i]}')
    
a = 15
for x in v1: 
    if (x < a):
        print(x)
    else:
        break

5
1
3
15
4
5
1
3
15
4
v1[0]=5
v1[1]=1
v1[2]=3
v1[3]=15
v1[4]=4
5
1
3


In [37]:
v = np.zeros(3)
for i in range(v.shape[0]):
    v[i] = \
        float(input(f'Introduce v[{i}]:'))

Introduce v[0]:1
Introduce v[1]:2
Introduce v[2]:3


Calcular el máximo y la media

In [38]:
v = v1
media = 0
for x in v: 
    media = media + x
    
media = media/v.shape[0]
print(f'Media nuestra: {media}')

ma = v[0]
# ma = float('-Inf')
for x in v: 
    if x > ma:
        ma = x
        
print(f'Máximo nuestro: {ma}')

# También con el API de numpy:
print(f'Máximo: {v.max()} \nMínimo: {v.min()} \nMedia: {v.mean()}')

Media nuestra: 5.6
Máximo nuestro: 15
Máximo: 15 
Mínimo: 1 
Media: 5.6


## Listas

Resumen rápido: 
* Las listas nos permiten almacenar distintos elementos de cualquier tipo.
* Se puede acceder a sus elementos de forma similar a las matrices 
* Existen funciones para añadir (`append()`) y extraer eliminando (`pop()`) elementos al final de la lista. 

In [39]:
# Declaración de lista vacía
lista = list()
lista.append(5)
lista.append(True)
lista.append('hola')
print(lista)

for i in lista:
    print(type(i))
    
print(lista.pop())
print(lista.pop())
print(lista.pop())

# Declaración de lista con elementos
lista = [1,2, True, 'hola']

[5, True, 'hola']
<class 'int'>
<class 'bool'>
<class 'str'>
hola
True
5


In [40]:
lista[2:]

[True, 'hola']