# Práctica VI

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/javism/fi2022-2023/blob/main/practica06/practica06.ipynb)

https://github.com/javism/fi2022-2023/blob/main/practica06/practica06.ipynb

* Vectores y Matrices: almacenan este tipo de datos con contenido numérico (bool, int, float). Habitualmente no añadimos y quitamos elementos salvo con operaciones puntuales de contatenación. 
* Listas: tipo de datos para almacenar otros datos de cualquier tipo. Están diseñados como estructura dinámica en la que añadir y extraer elementos habitualmente. 

Recursos: 
* [Cómo resolver sistemas de ecuaciones lineales con numpy](https://joanby.github.io/bookdown-algebra/ecuaciones-y-sistemas-lineales-con-r-python-y-octave.html#trabajando-con-python)

## Vectores y Matrices

Utilizaremos la biblioteca `numpy` para crear matrices y vector. Por convención siempre se nombra como `np`

Crear una matriz o vector con valores concretos. Observa las diferentes formas (`shape`) que adquieren. 

In [56]:
import numpy as np

# Vector
M = np.array([1,2,3])
print(M)
print(M.shape)

# "Matriz"
M = np.array([[1,2,3]])
print(M)
print(M.shape)

# Matriz
M = np.array([[1,2,3],[4,5,6]])
print(M)
print(M.shape)

# "Matriz"
M = np.array([[1],[2],[3]])
print(M)
print(M.shape)


[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1]
 [2]
 [3]]
(3, 1)


Otra opción para crear matrices es directamente crearlas con ceros, unos o números aleatorios

In [57]:
M = np.zeros(3)
print(M)
M = np.zeros([3,3])
print(M)

# Observa las diferencias
z = np.zeros([3])
z
z = np.zeros([3,1])
z
z = np.ones([3,2])
print(z)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


El módulo `np.random` nos permite generar (o muestrear) números alatorios de distintas distribuciones. Por defecto se usa la distribución uniforme para generar números en 0 y 1, pero también se pueden generar enteros de la uniforme u otros números de la distribución normal, Poison, etc. 

In [58]:
M = np.random.random([1,4])
M

array([[0.93930778, 0.44551489, 0.2006587 , 0.47424093]])

In [59]:
M = np.random.randint(-10,10,(3,4))
M

array([[  3,  -1,   4,   4],
       [ -1,   5, -10,  -1],
       [  6,   3,   2,   5]])

In [60]:
# Números aleatorios con la distribución normal con media 3 y varianza 2
Mn = np.random.normal(3, 2, (3,4))
Mn

array([[ 0.52907791,  1.1109026 ,  4.84641016,  3.32508372],
       [ 1.776943  ,  6.14571975,  2.31328402,  2.36737481],
       [ 2.33745289,  6.7578469 , -0.50796628,  1.94084298]])

### Acceso a elementos de la matriz

Ejemplos básicos para acceder a:
* la primera fila de la matriz completa
* el primer elemento de la primera fila de la matriz
* la primera fila de la matriz completa explícitamente con :
* la primera columna de la matriz
* la última columna de la matriz (podríamos poner -2, -3, etc.)

In [61]:
print(M)

[[  3  -1   4   4]
 [ -1   5 -10  -1]
 [  6   3   2   5]]


In [62]:
M[0,]

array([ 3, -1,  4,  4])

In [63]:
M[0,0]

3

In [64]:
M[0,:]

array([ 3, -1,  4,  4])

In [65]:
M[:,0]

array([ 3, -1,  6])

In [66]:
M[:,-1]

array([ 4, -1,  5])

In [67]:
vector = M[2,:]
vector

array([6, 3, 2, 5])

### Contatenar matrices

Se pueden concatenar matrices siempre que las dimensiones de las matrices cumplan las condiciones de álgebra lineal

In [52]:
M1 = np.array([1,2,3])
M2 = np.array([3, -4, 5, 6])
M3 = np.concatenate([M1,M2])
print(M3)

# Esto generaría un error
#M1 = np.array([[1,2,3]])
#M2 = np.array([3, -4, 5, 6])
#M3 = np.concatenate([M1,M2])

[ 1  2  3  3 -4  5  6]


## Listas

Resumen rápido: 
* Las listas nos permiten almacenar distintos elementos de cualquier tipo.
* Se puede acceder a sus elementos de forma similar a las matrices 
* Existen funciones para añadir (`append()`) y extraer eliminando (`pop()`) elementos al final de la lista. 

In [22]:
# Declaración de lista vacía
lista = list()
lista.append(5)
lista.append(True)
lista.append('hola')
print(lista)

for i in lista:
    print(type(i))
    
print(lista.pop())
print(lista.pop())
print(lista.pop())

# Declaración de lista con elementos
lista = [1,2, True, 'hola']

[5, True, 'hola']
<class 'int'>
<class 'bool'>
<class 'str'>
hola
True
5


In [26]:
lista[2:]

[True, 'hola']